name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        # אם הקוד בתיקייה פנימית, שנה את ה-'.' לשם התיקייה (למשל './frontend')
        run: bun install
        working-directory: . 

      - name: Build
        # הוספתי פה פקודה שתעקוף את השגיאות ותבנה ישר
        run: bun run vite build
        working-directory: .

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # וודא שהנתיב לתיקיית dist נכון
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
